"""See CallForest."""

import attr
import pandas as pd  # type: ignore


@attr.frozen
class CallForest:
    """Deals with the callgraph (forest) generated by cpu_timer.

    Other analysis should never read the raw dataframe of cpu_timer
    frames; Instead, they should delegate to this module.

    That way, I can easily change how cpu_timer works.

    """

    _data: pd.DataFrame = attr.ib()
